### ISSUE TITLE
GIFs cannot be saved when running as module

### ISSUE THREAD

**Issue by frankrolf** [typemytype/drawbot#77]
```
Traceback (most recent call last):
  File "glyphDiff.py", line 61, in <module>
    saveImage(os.path.expanduser('~/Desktop/comparison gifs %s/comparison_%s.gif' % (masterNumber, gName)))
  File "/Library/Python/2.7/site-packages/drawBot/drawBotDrawingTools.py", line 301, in saveImage
    context.saveImage(path, multipage)
  File "/Library/Python/2.7/site-packages/drawBot/context/baseContext.py", line 1397, in saveImage
    self._saveImage(path, multipage)
  File "/Library/Python/2.7/site-packages/drawBot/context/pdfContext.py", line 55, in _saveImage
    self._writeDataToFile(self._pdfData, path, multipage)
  File "/Library/Python/2.7/site-packages/drawBot/context/gifContext.py", line 45, in _writeDataToFile
    generateGif(inputPaths, path, self._delayData)
  File "/Library/Python/2.7/site-packages/drawBot/context/tools/gifTools.py", line 59, in generateGif
    _executeCommand(cmds)
  File "/Library/Python/2.7/site-packages/drawBot/context/tools/gifTools.py", line 20, in _executeCommand
    resultCode = subprocess.call(cmds, stdout=gifsicleStdOut, stderr=gifsicleStdErr, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by typemytype** [comment]
mm, `setupAsModule.py` does not copy the required tools...

**Comment by typemytype** [comment]
this should solve it
https://github.com/typemytype/drawbot/commit/11ac5ac7df7a24d5172e266734694be9d3a01283

please re-install

**Comment by frankrolf** [comment]
I updated the repository, removed the old module and installed the new one. 
Unfortunately, I still get the same message as above. If I change the export file type, everything works flawlessly.

**Comment by typemytype** [comment]
does the setup file copies all executable tools nicely to the site packages? with proper permissions?

**Comment by frankrolf** [comment]
It seems to. (Although I need to run `sudo python installAsModule.py install` because the normal installation fails.

However, there is no trace of gifsicle.
In `giftools.py` I see the following code:
```
gifsiclePath = os.path.join(os.path.dirname(__file__), "gifsicle")
if not os.path.exists(gifsiclePath):
    gifsiclePath = os.path.join(os.getcwd(), "gifsicle")
```

This file doesn’t exist in the site-packages folder.
If I take the `gifsicle` file from `/Applications/DrawBot.app/Contents/Resources/` and place it next to `giftools.py`, everything works.

**Comment by typemytype** [comment]
I guess this should be solved here

https://github.com/typemytype/drawbot/commit/fdb4f9c1bf121772387183f71223cbd0153d1901
